# Copyright (c) 2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/cgnd/zephyr-pre-commit-hooks
    rev: v1.0.0
    hooks:
    - id: zephyr-checkpatch-diff
  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
    - id: reuse
