# Copyright (c) 2022-2023 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: 0.8

  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.8.0
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-ncs.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - mbedtls-nrf
          - mcuboot
          - net-tools
          - nrfxlib
          - segger
          - qcbor
          - tfm-mcuboot
          - tinycrypt
          - trusted-firmware-m
          - zcbor

    - name: golioth-zephyr-boards
      path: deps/modules/lib/golioth-boards
      revision: v1.0.1
      url: https://github.com/golioth/golioth-zephyr-boards

    - name: libostentus
      path: deps/modules/lib/libostentus
      revision: v1.0.0
      url: https://github.com/golioth/libostentus

    - name: zephyr-network-info
      path: deps/modules/lib/network-info
      revision: v1.0.1
      url: https://github.com/golioth/zephyr-network-info

    - name: sensirion-embedded-common
      path: app/external/sensirion/embedded-common
      revision: f0a64d166266b364c558d407739c96fdc5395df1
      url: https://github.com/golioth/sensirion-embedded-common.git

    - name: sensirion-embedded-i2c-scd4x
      path: app/external/sensirion/embedded-i2c-scd4x
      revision: fbfd86e8ea371894ae6473c48cf4f425c54360f0
      url: https://github.com/golioth/sensirion-embedded-i2c-scd4x.git

    - name: sensirion-embedded-sps
      path: app/external/sensirion/embedded-sps
      revision: ef781982b917249ebdafd30673b281b7c3f0764a
      url: https://github.com/golioth/sensirion-embedded-sps.git
  self:
    path: app
