manifest:
  version: 0.7

  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: a5a177d8cc9d49b913178774e6ff9e7c86192168
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-ncs.yml
        path-prefix: deps
        name-allowlist:
          - nrf
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - mbedtls-nrf
          - mcuboot
          - net-tools
          - nrfxlib
          - tfm-mcuboot
          - trusted-firmware-m
          - qcbor
          - segger
          - tinycrypt

    - name: golioth-zephyr-boards
      path: app/golioth-boards
      revision: 16dd0ef2d13a8e95ba923ee014424f5a3f1009cf
      url: git@github.com:golioth/golioth-zephyr-boards.git

    - name: libostentus
      path: app/src/libostentus
      revision: 504f40aba1502b1dbea4d4710a3a438913948b40
      url: git@github.com:golioth/libostentus.git

    - name: sensirion-embedded-common
      path: app/external/sensirion/embedded-common
      revision: 66cf952d54a51b537f4573e7be1a7c4451a84b48
      url: https://github.com/golioth/sensirion-embedded-common.git

    - name: sensirion-embedded-i2c-scd4x
      path: app/external/sensirion/embedded-i2c-scd4x
      revision: fbfd86e8ea371894ae6473c48cf4f425c54360f0
      url: https://github.com/golioth/sensirion-embedded-i2c-scd4x.git

    - name: sensirion-embedded-sps
      path: app/external/sensirion/embedded-sps
      revision: ef781982b917249ebdafd30673b281b7c3f0764a
      url: https://github.com/golioth/sensirion-embedded-sps.git
  self:
    path: app
